version: '3'

volumes:
  node_modules_store:
services:
  node: &app_base
    image: node:16
    tty: true
    working_dir: /workspace
    volumes:
      - .:/workspace
      - node_modules_store:/workspace/node_modules
    environment:
      HOST: 0.0.0.0
      PORT: 3000
    restart: always

  nuxtjs:
    <<: *app_base
    ports:
      - 3000:3000
    command: yarn dev
