openapi: 3.0.3
info:
  title: Starrydata API
  version: '3.0'
  description: '  '
servers:
  - url: 'http://localhost:3100'
paths:
  /papers:
    get:
      summary: Get Papers
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                description: ''
                x-examples:
                  example-1:
                    - type: articles
                      id: '1'
                      attributes:
                        title: Rails is Omakase
                      relationships:
                        author:
                          links:
                            self: /articles/1/relationships/author
                            related: /articles/1/author
                          data:
                            type: people
                            id: '9'
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Paper'
              examples:
                example-1:
                  value:
                    - SID: 1
                      title: Decoupling Interrelated Parameters for Designing High Performance Thermoelectric Materials
                      authors: 'C. Xiao, Z. Li, K. Li, P. Huang, Y. Xie,'
                      identifier: 00000001_Xiao_2014
                      DOI: 10.1021/ar400290f
                      figures: 1
                      samples: 1
                    - SID: 2
                      title: Decoupling Interrelated Parameters for Designing High Performance Thermoelectric Materials
                      authors: 'C. Xiao, Z. Li, K. Li, P. Huang, Y. Xie,'
                      identifier: 00000001_Xiao_2014
                      DOI: 10.1021/ar400290f
                      figures: 1
                      samples: 1
                    - SID: 3
                      title: Decoupling Interrelated Parameters for Designing High Performance Thermoelectric Materials
                      authors: 'C. Xiao, Z. Li, K. Li, P. Huang, Y. Xie,'
                      identifier: 00000001_Xiao_2014
                      DOI: 10.1021/ar400290f
                      figures: 1
                      samples: 1
                    - SID: 4
                      title: Decoupling Interrelated Parameters for Designing High Performance Thermoelectric Materials
                      authors: 'C. Xiao, Z. Li, K. Li, P. Huang, Y. Xie,'
                      identifier: 00000001_Xiao_2014
                      DOI: 10.1021/ar400290f
                      figures: 1
                      samples: 1
                    - SID: 5
                      title: Decoupling Interrelated Parameters for Designing High Performance Thermoelectric Materials
                      authors: 'C. Xiao, Z. Li, K. Li, P. Huang, Y. Xie,'
                      identifier: 00000001_Xiao_2014
                      DOI: 10.1021/ar400290f
                      figures: 1
                      samples: 1
                    - SID: 6
                      title: Decoupling Interrelated Parameters for Designing High Performance Thermoelectric Materials
                      authors: 'C. Xiao, Z. Li, K. Li, P. Huang, Y. Xie,'
                      identifier: 00000001_Xiao_2014
                      DOI: 10.1021/ar400290f
                      figures: 1
                      samples: 1
        '201':
          description: Created
      operationId: get-papers
      x-internal: false
    parameters: []
  '/papers/{paperId}':
    parameters:
      - schema:
          type: string
        name: paperId
        in: path
        required: true
    get:
      summary: get paper
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                x-examples:
                  example-1:
                    type: articles
                    id: '1'
                    attributes:
                      title: Rails is Omakase
                properties:
                  data:
                    type: object
                    properties:
                      type:
                        type: string
                      id:
                        type: string
                      attributes:
                        $ref: '#/components/schemas/Paper'
      operationId: get-papers-paperId
  /databases:
    get:
      summary: get databases
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                x-examples:
                  example-1:
                    - type: articles
                      id: '1'
                      attributes:
                        title: Rails is Omakase
                      relationships:
                        author:
                          links:
                            self: /articles/1/relationships/author
                            related: /articles/1/author
                          data:
                            type: people
                            id: '9'
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Database'
              examples:
                example-1:
                  value:
                    data:
                      - type: databases
                        id: 1
                        attributes:
                          name: General DB
                        relationships:
                          figures:
                            data: []
                            meta:
                              totalFigures: 31480
                          papers:
                            data: []
                            meta:
                              totalPapers: 30449
                          samples:
                            meta:
                              totalSamples: 40458
                            data: []
                      - type: databases
                        id: 2
                        attributes:
                          name: Thermoelectric Materials DB
                        relationships:
                          papers:
                            data: []
                            meta:
                              totalPapers: 23870
                          figures:
                            data: []
                            meta:
                              totalFigures: 29260
                          samples:
                            meta:
                              totalSamples: 34513
                            data: []
                      - type: databases
                        id: 3
                        attributes:
                          name: Magnetic Materials DB
                        relationships:
                          papers:
                            data: []
                            meta:
                              totalPapers: 4103
                          figures:
                            data: []
                            meta:
                              totalFigures: 1494
                          samples:
                            meta:
                              totalSamples: 3849
                            data: []
                      - type: databases
                        id: 4
                        attributes:
                          name: Condensed Matter DB
                        relationships:
                          papers:
                            data: []
                            meta:
                              totalPapers: 349
                          figures:
                            data: []
                            meta:
                              totalFigures: 509
                          samples:
                            meta:
                              totalSamples: 1374
                            data: []
                      - type: databases
                        id: 5
                        attributes:
                          name: High Thermal Conductivity Materials DB
                        relationships:
                          papers:
                            data: []
                            meta:
                              totalPapers: 179
                          figures:
                            data: []
                            meta:
                              totalFigures: 250
                          samples:
                            meta:
                              totalSamples: 519
                            data: []
                      - type: databases
                        id: 6
                        attributes:
                          name: Piezoelectric Materials
                        relationships:
                          papers:
                            data: []
                            meta:
                              totalPapers: 134
                          figures:
                            data: []
                            meta:
                              totalFigures: 0
                          samples:
                            meta:
                              totalSamples: 0
                            data: []
                      - type: databases
                        id: 7
                        attributes:
                          name: Hyper Material
                        relationships:
                          papers:
                            data: []
                            meta:
                              totalPapers: 76
                          figures:
                            data: []
                            meta:
                              totalFigures: 146
                          samples:
                            meta:
                              totalSamples: 262
                            data: []
                      - type: databases
                        id: 8
                        attributes:
                          name: Project TtoH
                        relationships:
                          papers:
                            data: []
                            meta:
                              totalPapers: 0
                          figures:
                            data: []
                            meta:
                              totalFigures: 0
                          samples:
                            meta:
                              totalSamples: 0
                            data: []
                example-2:
                  value:
                    data:
                      - type: string
                        id: 0
                        attributes:
                          name: string
                        relationships:
                          papers:
                            data:
                              - type: string
                                id: 0
                                attributes:
                                  DOI: string
                                  title: string
                            meta:
                              totalPapers: 0
                          figures:
                            data:
                              - type: string
                                id: string
                                attributes: {}
                            meta:
                              totalFigures: 0
                          samples:
                            data:
                              - type: string
                                id: string
                                attributes: {}
                            meta:
                              totalSamples: 0
      operationId: get-databases
      description: 論文一覧取得
    parameters: []
components:
  schemas:
    Paper:
      title: Paper
      type: object
      description: ''
      properties:
        type:
          type: string
        id:
          type: number
        attributes:
          type: object
          properties:
            DOI:
              type: string
            title:
              type: string
    Database:
      title: Database
      type: object
      properties:
        type:
          type: string
        id:
          type: number
        attributes:
          type: object
          properties:
            name:
              type: string
        relationships:
          type: object
          properties:
            papers:
              type: object
              properties:
                data:
                  type: array
                  items:
                    $ref: '#/components/schemas/Paper'
                meta:
                  type: object
                  properties:
                    totalPapers:
                      type: number
            figures:
              type: object
              properties:
                data:
                  type: array
                  items:
                    $ref: '#/components/schemas/Figure'
                meta:
                  type: object
                  properties:
                    totalFigures:
                      type: number
            samples:
              type: object
              properties:
                data:
                  type: array
                  items:
                    $ref: '#/components/schemas/Sample'
                meta:
                  type: object
                  properties:
                    totalSamples:
                      type: number
      description: ''
      x-examples:
        example-1:
          value:
            type: databases
            id: 1
            attributes:
              name: General DB
            relationships:
              figures:
                data: []
                meta:
                  totalFigures: 31480
              papers:
                data: []
                meta:
                  totalPapers: 30449
              samples:
                meta:
                  totalSamples: 40458
                data: []
    Figure:
      title: Figure
      type: object
      properties:
        type:
          type: string
        id:
          type: string
        attributes:
          type: object
    Sample:
      title: Sample
      type: object
      properties:
        type:
          type: string
        id:
          type: string
        attributes:
          type: object
